from typing import List, Dict, Any, Union, Tuple, Set 
def waste_calculation_calculate(population:Dict[str, Any], location:str) -> str:
	"""
	waste_calculation_calculate : Calculates the estimated waste generated by different population sizes in a specific location.    
	Parameters:
	population (Dict[str, Any]): The description of population. 'adults' is the number of adults in the household. 'children' is the number of children. 'singles' is the number of single adults living alone.
	location (str): The city where the population resides.

	Required Parameter = [population,location,]

	"""
	return 'Success'

tools = [waste_calculation_calculate]
